#!/bin/sh -e

# This script must be run as ./graph-hsdir-set-instability .

gnuplot >out/hsdir-set-instability-graph.ps <<EOF
set terminal postscript color solid
load "graph-hsdir-set-instability.gnuplot"
EOF

